### PR TITLE
Updated the screenshot of the README file after adding a property to add drawable and padding to the chip text

### PR DESCRIPTION
**Pull request by kavitamp**
### Description
As new properties are added to have icons and padding to the icons around the chip text, the new screenshot needs to be updated in the README file

### CODE REVIEW

**Comment by kavitamp** [comment]
@jahirfiquitiva,
Please let me know if you have any feedback.
Thank you!

**Comment by jahirfiquitiva** [comment]
hi @kavitamp please do not change the url in the readme, but instead change the image file, thanks

**Comment by kavitamp** [comment]
> hi @kavitamp please do not change the url in the readme, but instead change the image file, thanks

@jahirfiquitiva Have updated it, please check

**Comment by jahirfiquitiva** [comment]
@kavitamp awesome, thanks!

**Pull request merged**
