### PR TITLE
Enhancement: Properties to have icons and padding to the icons around the chip text

### PR DESCRIPTION
**Pull request by kavitamp**
### Description
Added extra properties to have icons and padding to the icons at the top, bottom, left, and right of the text.

### Motivation
This provides the flexibility to customize the ChipView. Users can have a drawable icon not just at the start or the end of the view, it can be at any of the four directions with customizable padding.

Chip

Please let me know if you have any feedback.
Thank you!

### CODE REVIEW

**Comment by kavitamp** [comment]
Hi @jahirfiquitiva,
I have added some properties to the ChipView, please take a look.
Thanks!

**Comment by jahirfiquitiva** [comment]
hi @kavitamp 
thank you so much for your contribution. there's a bunch of unnecessary format changes, would you mind reverting those? 😅

**Comment by kavitamp** [comment]
> hi @kavitamp thank you so much for your contribution. there's a bunch of unnecessary format changes, would you mind reverting those? 😅

Sure, I have fixed it, please check.

**Review by jahirfiquitiva — APPROVED** [review]

**Comment by jahirfiquitiva** [comment]
Thank you so much @kavitamp 🎉

**Pull request merged**
